language: python
python:
  - "2.7"
install: sudo apt-get update && sudo apt-get install -y python-virtualenv g++ ffmpeg && ./bootstrap.sh
script: ./bin/python bin/list-tests.py
notifications:
  irc:
    - "irc.mozilla.org#ateam"
  email:
    recipients:
      - wlachance@mozilla.com
