language: python
python:
  - "2.7"
install: sudo apt-get update && sudo apt-get install -y python-virtualenv g++ ffmpeg && ./bootstrap.sh
script: ./bin/python bin/list-tests.py
notifications:
  # irc notifications not working with irc.mozilla.org, see: https://github.com/travis-ci/travis-ci/issues/436
  # (leaving it configured in case this is fixed at some point)
  irc:
    - "irc.mozilla.org#ateam"
  email:
    recipients:
      - wlachance@mozilla.com
